### ISSUE TITLE
Node requirement is actually >= 7.6.0

### ISSUE THREAD

**Issue by JamesMGreene** [jonschlinkert/delete-empty#10]
The "package.json" file reports the Node engine requirement as `node@>=6`. However, your use of `async`/`await` functionality actually requires `node@>=7.6.0`.

Please either eliminate the use of the `async` functions or else correct the Node engine requirement in your "package.json". My personal preference would be to remove the `async` functions... although they are awesome, it is more frustrating to not be able to use a good utility library because of it requires such a modern version of Node only due to syntactic sugar.

Thanks!

**Comment by JamesMGreene** [comment]
For now, I am using `v1.x` to make it work with `node@6.x`.

**Comment by jonschlinkert** [comment]
we should probably just make it 8.0. want to do a pr?

**Comment by doowb** [comment]
This has been fixed.
