### ISSUE TITLE
Do not log when used as dependency in a non-interractive way

### ISSUE THREAD

**Issue by Alex-D** [jonschlinkert/delete-empty#11]
When I require the module and use it in my code, it logs via `log-ok` but I do not want these logs in my app output.

How can we do that?

**Comment by doowb** [comment]
This will only log ok if the `verbose` option is set to `true`. If that option is not set to `true` and it's still logging, please provide example code of how you're using the module.

**Comment by doowb** [comment]
I was looking at the current code in version `2.0.0` which requires explicitly setting `verbose: true` on options to log ok. If you're using an older version, then you can set `verbose: false` to disable the logging.

**Comment by Alex-D** [comment]
OK thanks! :)
