### ISSUE TITLE
you are not zhongyong a 

### ISSUE THREAD

**Issue by huaizhiY** [jonschlinkert/delete-empty#13]
console.log(__dirname + '\\dist\\');
deleteEmpty(__dirname + '\\dist\\')
  .then(deleted => console.log(deleted)) //=> ['foo/aa/', 'foo/a/cc/', 'foo/b/', 'foo/c/']
  .catch(console.error);
gulp remove failde

**Comment by jonschlinkert** [comment]
closing since this library was refactored
