### ISSUE TITLE
Version 3.0.0 doesnt seem to work.

### ISSUE THREAD

**Issue by rodrigograca31** [jonschlinkert/delete-empty#14]
```javascript
deleteEmpty('foo/')
  .then(deleted => console.log(deleted)) //=> ['foo/aa/', 'foo/a/cc/', 'foo/b/', 'foo/c/']
  .catch(console.error);
```

does nothing to the folder if we are in version 3.0.0, outputs `undefined`

**Comment by Nutropy** [comment]
I can confirm this issue.
When using it with a relative path the `isValidDir` function returns false because of `startsWith(dir, cwd)` fails, where `dir`=resolved absolute path and `cwd`= relative part of it.

IMHO it should have been checked with the `path-ends-with` package.

**Comment by hectorfarahani** [comment]
I have the same problem. However, the CLI is working.

**Comment by jevgenigavrilov** [comment]
@rodrigograca31 did you manage to find a workaround for this?

**Comment by jevgenigavrilov** [comment]
nevermind, used [remove-empty-directories](https://www.npmjs.com/package/remove-empty-directories) package. Did just what I wanted.

**Comment by kristian** [comment]
As mentioned above the `isValidDir` function fails for relative paths. Thus as a workaround until this is fixed you can call a `path.resolve(...)` before calling the `deleteEmpty` function.

**Comment by jonschlinkert** [comment]
closing since this was refactored
