### ISSUE TITLE
Consumes a lot of memory

### ISSUE THREAD

**Issue by eight04** [jonschlinkert/delete-empty#15]
![image](https://user-images.githubusercontent.com/1324510/71489441-97faf800-2860-11ea-8331-3f6fe1cda0f3.png)
Why does it use so many resources for a simple task?

**Comment by eight04** [comment]
I decided to kill the process after it grew to 750 mb.
![image](https://user-images.githubusercontent.com/1324510/71490271-fe821500-2864-11ea-9de9-25d9ec6754ad.png)

**Comment by doowb** [comment]
Can you show some code on how you're using `delete-empty` and also, if you're specifying a large directory of files/folder or one that is deeply nested, there could be a lot of memory usage.

**Comment by eight04** [comment]
I'm using the CLI in a large folder by running `delete-empty .`

I guess it may be better if we can 

1. Avoid collecting all empty folders in the [empty array](https://github.com/jonschlinkert/delete-empty/blob/6ae34547663e6845c3c98b184c606fa90ef79c0a/index.js#L67)
2. Switch to [`opendir` API](https://nodejs.org/api/fs.html#fs_fspromises_opendir_path_options).

Is that an option for this project?

**Comment by jonschlinkert** [comment]
Closing since this library was refactored and this may no longer be applicable.
