### ISSUE TITLE
Callback doesn't default to an empty function

### ISSUE THREAD

**Issue by Dan503** [jonschlinkert/delete-empty#6]
This doesn't work

```
deleteEmpty('folder/');
```

But this does:

```
deleteEmpty('folder/',function(){});
```

**Comment by jonschlinkert** [comment]
right, that's an anti-pattern for async usage at this level. Implementors can do what you did in your example, or you could use `deleteEmpty.sync`.

**Comment by Dan503** [comment]
If all you want to do is apply a quick asynchronous folder clean then this syntax should be allowed

```
deleteEmpty('folder/');
```

The callback parameter just needs this applied to it

```
callback = typeof callback === 'undefined' ? callback  : function(){};
```

I don't see why you want to force your users to use this syntax:

```
deleteEmpty('folder/',function(){});
```

It's unintuitive having to write that.
